# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome to this place :) #
name: Hongyou Lin # ex. Hongyou Lin
email: hlin1@haverford.edu
location: Philadelphia, PA, USA # ex. Philadelphia, PA
company: Haverford College
company_url: https://www.haverford.edu/
github_url: https://github.com/HongyouLin97 # ex. https://github.com/HongyouLin97
github_username: HongyouLin97 # ex. HongyouLin97
description: This is a personal website of Hongyou Lin, who is a Haverford College student, class of 2020. Major in Physics, but enjoy programming.
favicon: favicon.ico # Image must be in assets/images
repository: HongyouLin97/hongyoulin.github.io # ex. HongyouLin97/hongyoulin.github.io
# facebook_username: Hongyou Lin
# facebook_url: 
# linkedin_username: Hongyou Lin
# linkedin_url: 

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: https://zhanpengwang888.github.io/
# url: http://localhost:4000

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: HongyouLin97githubio.disqus.com # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /projects
    label: Projects

  -
    href: /blog
    label: Blog

  -
    href: /useful_links
    label: Useful Links

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-123175385-1'  # ex. UA-72165600-X

google_analytics: UA-123175385-1

# For about.html.
skill_software_keywords: [Python, Java, hack, C/C++, MySQL, SQLite, Racket, Scheme, Stata 14, Processing]
skill_web_keywords: [HTML5, CSS, JavaScript, JQuery, NodeJS, Flask, Django]
skill_languages: [English, Hakka, Mandarin, Cantonese, Japanese, French, Latin]
courses_taken_so_far: [CIS519 Applied Machine Learning, CMSC356 Concurrency and Co-Design in Operating Systems,
                      MATH/ECON/CMSC210 Linear Optimization, ECON247 Financial Accounting, 
                      CMSC395 Mobile Development, CMSC340 Analysis of Algorithms, CMSC240 Computer Organization ,CMSC355 Operating System,
                      CMSC311 Computer Security, CMSC245 Principle to Programming Languages, ECON304 Intro to Econometrics,
                      MATH215 Linear Algebra, CMSC231 Discrete Mathematics, ECON204 Economic Statistics with Calculus, 
                      CMSC105 Intro to CS, CMSC106 Intro to Data Structure, ECON105 Intro to Economics, LING101 Intro to Linguistics,
                      JNSE001-002 First Year Japanese Intensive]